--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OguzhanUmutlu/ComplexPets
build-by-default: true
branches:
- main
projects:
  ComplexPets:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^1.0.0
      - src: muqsit/invmenu/invmenu
        version: ^4.1
...
